[project]
name = "tradematic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.11"
dependencies = [
    "aiohttp>=3.13.0",
    "django==4.2.23",
    "matplotlib>=3.9.4",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "tensorboard==2.19.0",
    "tensorboard-data-server==0.7.2",
    "tensorflow==2.19.0",
    "tinkoff-investments>=0.2.0b117",
    "tqdm>=4.67.1",
    "cryptography>=47.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.14.0",
]

[tool.ruff]
fix = true
line-length = 120
target-version = "py312"

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint]
ignore = ["I001","F403","F405"]
preview = true

[tool.mypy]
plugins = ['pydantic.mypy']
strict=true
