from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
CSV_PATH = DATA_DIR / "news_dataset.csv"

REQUEST_TIMEOUT = 30.0
ARTICLE_FETCH_CONCURRENCY = 8
SOURCE_FETCH_CONCURRENCY = 4
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/123.0.0.0 Safari/537.36"
)

MIN_ARTICLE_WORDS = 300
TARGET_CHUNK_WORDS = 350
MIN_CHUNK_WORDS = 150
CHUNK_OVERLAP_WORDS = 50
CHUNK_SEPARATOR = " ||| "

CBR_SOURCE = "ЦБ РФ"
CBR_ROW_URL = "https://www.cbr-xml-daily.ru/"
CBR_ENDPOINTS = (
    {"url": "https://www.cbr-xml-daily.ru/daily_json.js", "format": "json"},
    {"url": "https://www.cbr-xml-daily.com/daily_json.js", "format": "json"},
    {"url": "https://www.cbr.ru/scripts/XML_daily.asp", "format": "xml"},
)
CBR_TARGET_CODES = (
    "USD",
    "EUR",
    "CNY",
    "BYN",
    "KZT",
    "GBP",
    "JPY",
    "CHF",
    "AED",
    "AMD",
    "AUD",
    "AZN",
    "BGN",
    "BRL",
    "CAD",
    "CZK",
    "DKK",
    "EGP",
    "GEL",
    "HKD",
    "HUF",
    "IDR",
    "INR",
    "KGS",
    "KRW",
    "MDL",
    "NOK",
    "NZD",
    "PLN",
    "QAR",
    "RON",
    "RSD",
    "SEK",
    "SGD",
    "TJS",
    "TMT",
    "TRY",
    "UAH",
    "UZS",
    "XDR",
    "ZAR",
)

NEWS_SOURCES = (
    {
        "name": "РБК",
        "section_url": "https://www.rbc.ru/finances/",
        "allowed_domains": ("www.rbc.ru", "rbc.ru"),
        "language": "ru",
    },
    {
        "name": "Коммерсантъ",
        "section_url": "https://www.kommersant.ru/",
        "allowed_domains": ("www.kommersant.ru", "kommersant.ru"),
        "language": "ru",
    },
    {
        "name": "ТАСС",
        "section_url": "https://tass.ru/ekonomika",
        "rss_url": "https://tass.ru/rss/v2.xml",
        "allowed_domains": ("tass.ru", "www.tass.ru"),
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
        "language": "ru",
    },
    {
        "name": "Ведомости",
        "section_url": "https://www.vedomosti.ru/finance",
        "allowed_domains": ("www.vedomosti.ru", "vedomosti.ru"),
        "language": "ru",
    },
    {
        "name": "Лента.ру Экономика",
        "section_url": "https://lenta.ru/rubrics/economics/",
        "rss_url": "https://lenta.ru/rss/news/economics",
        "allowed_domains": ("lenta.ru", "www.lenta.ru"),
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
        "language": "ru",
    },
    {
        "name": "Лента.ру Мир",
        "section_url": "https://lenta.ru/rubrics/world/",
        "rss_url": "https://lenta.ru/rss/news/world",
        "allowed_domains": ("lenta.ru", "www.lenta.ru"),
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
        "language": "ru",
    },
    {
        "name": "МК Экономика",
        "section_url": "https://www.mk.ru/economics/",
        "rss_url": "https://www.mk.ru/rss/economics/index.xml",
        "allowed_domains": ("www.mk.ru", "mk.ru"),
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
        "language": "ru",
    },
    {
        "name": "Газета.Ru Бизнес",
        "section_url": "https://www.gazeta.ru/business/",
        "allowed_domains": ("www.gazeta.ru", "gazeta.ru"),
        "language": "ru",
    },
    {
        "name": "Forbes Russia",
        "section_url": "https://www.forbes.ru/finansy",
        "allowed_domains": ("www.forbes.ru", "forbes.ru"),
        "language": "ru",
    },
    {
        "name": "Euronews RU Business",
        "section_url": "https://ru.euronews.com/business",
        "allowed_domains": ("ru.euronews.com", "euronews.com"),
        "language": "ru",
    },
    {
        "name": "BBC Russian",
        "section_url": "https://www.bbc.com/russian",
        "allowed_domains": ("www.bbc.com", "bbc.com", "www.bbc.co.uk", "bbc.co.uk"),
        "language": "ru",
    },
    {
        "name": "Sputnik Беларусь",
        "section_url": "https://sputnik.by/economy/",
        "allowed_domains": ("sputnik.by", "www.sputnik.by"),
        "language": "ru",
    },
    {
        "name": "РИА Новости Экономика",
        "section_url": "https://ria.ru/economy/",
        "allowed_domains": ("ria.ru", "www.ria.ru"),
        "language": "ru",
    },
    {
        "name": "РИА Новости Мир",
        "section_url": "https://ria.ru/world/",
        "allowed_domains": ("ria.ru", "www.ria.ru"),
        "language": "ru",
    },
    {
        "name": "РБК Инвестиции",
        "section_url": "https://quote.ru/",
        "allowed_domains": ("quote.ru", "www.quote.ru"),
        "language": "ru",
    },
    {
        "name": "BFM",
        "section_url": "https://www.bfm.ru/news",
        "allowed_domains": ("www.bfm.ru", "bfm.ru"),
        "language": "ru",
    },
    {
        "name": "Banki.ru",
        "section_url": "https://www.banki.ru/news/",
        "allowed_domains": ("www.banki.ru", "banki.ru"),
        "language": "ru",
    },
    {
        "name": "Frank Media",
        "section_url": "https://frankmedia.ru/",
        "allowed_domains": ("frankmedia.ru", "www.frankmedia.ru"),
        "language": "ru",
    },
    {
        "name": "EADaily",
        "section_url": "https://eadaily.com/ru/news/economics/",
        "allowed_domains": ("eadaily.com", "www.eadaily.com"),
        "language": "ru",
    },
    {
        "name": "VC.ru",
        "section_url": "https://vc.ru/",
        "allowed_domains": ("vc.ru", "www.vc.ru"),
        "language": "ru",
    },
    {
        "name": "БелТА Экономика",
        "section_url": "https://www.belta.by/economics/",
        "allowed_domains": ("www.belta.by", "belta.by"),
        "language": "ru",
    },
    {
        "name": "Sputnik Казахстан",
        "section_url": "https://sputnik.kz/economy/",
        "allowed_domains": ("sputnik.kz", "www.sputnik.kz"),
        "language": "ru",
    },
    {
        "name": "Sputnik Армения",
        "section_url": "https://sputnikarm.ru/economy/",
        "allowed_domains": ("sputnikarm.ru", "www.sputnikarm.ru"),
        "language": "ru",
    },
    {
        "name": "DW Russian",
        "section_url": "https://www.dw.com/ru/%D1%82%D0%B5%D0%BC%D1%8B/%D1%8D%D0%BA%D0%BE%D0%BD%D0%BE%D0%BC%D0%B8%D0%BA%D0%B0/s-10022",
        "allowed_domains": ("www.dw.com", "dw.com"),
        "language": "ru",
    },
    {
        "name": "BBC Business",
        "section_url": "https://www.bbc.com/news/business",
        "rss_url": "http://feeds.bbci.co.uk/news/business/rss.xml",
        "allowed_domains": ("www.bbc.com", "bbc.com", "www.bbc.co.uk", "bbc.co.uk"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "BBC World",
        "section_url": "https://www.bbc.com/news/world",
        "rss_url": "http://feeds.bbci.co.uk/news/world/rss.xml",
        "allowed_domains": ("www.bbc.com", "bbc.com", "www.bbc.co.uk", "bbc.co.uk"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Guardian World",
        "section_url": "https://www.theguardian.com/world",
        "rss_url": "https://www.theguardian.com/world/rss",
        "allowed_domains": ("www.theguardian.com", "theguardian.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Guardian Business",
        "section_url": "https://www.theguardian.com/business",
        "rss_url": "https://www.theguardian.com/business/rss",
        "allowed_domains": ("www.theguardian.com", "theguardian.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CNBC News",
        "section_url": "https://www.cnbc.com/",
        "rss_url": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        "allowed_domains": ("www.cnbc.com", "cnbc.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CNBC World",
        "section_url": "https://www.cnbc.com/world/",
        "rss_url": "https://www.cnbc.com/id/100727362/device/rss/rss.html",
        "allowed_domains": ("www.cnbc.com", "cnbc.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 40,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "AP Business",
        "section_url": "https://apnews.com/hub/business",
        "rss_url": "https://apnews.com/hub/apf-business?output=rss",
        "allowed_domains": ("apnews.com", "www.apnews.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Yahoo Finance",
        "section_url": "https://finance.yahoo.com/news/",
        "rss_url": "https://finance.yahoo.com/news/rssindex",
        "allowed_domains": ("finance.yahoo.com", "www.finance.yahoo.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "MarketWatch",
        "section_url": "https://www.marketwatch.com/",
        "rss_url": "https://feeds.content.dowjones.io/public/rss/mw_topstories",
        "allowed_domains": ("www.marketwatch.com", "marketwatch.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "WSJ Markets",
        "section_url": "https://www.wsj.com/news/markets",
        "rss_url": "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
        "allowed_domains": ("www.wsj.com", "wsj.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Financial Times",
        "section_url": "https://www.ft.com/",
        "rss_url": "https://www.ft.com/?format=rss",
        "allowed_domains": ("www.ft.com", "ft.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Investing.com News",
        "section_url": "https://www.investing.com/news/",
        "rss_url": "https://www.investing.com/rss/news.rss",
        "allowed_domains": ("www.investing.com", "investing.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Nasdaq Markets",
        "section_url": "https://www.nasdaq.com/market-activity",
        "rss_url": "https://www.nasdaq.com/feed/rssoutbound?category=Markets",
        "allowed_domains": ("www.nasdaq.com", "nasdaq.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "OilPrice",
        "section_url": "https://oilprice.com/",
        "rss_url": "https://oilprice.com/rss/main",
        "allowed_domains": ("oilprice.com", "www.oilprice.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Kitco News",
        "section_url": "https://www.kitco.com/news/",
        "rss_url": "https://www.kitco.com/rss/news",
        "allowed_domains": ("www.kitco.com", "kitco.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "ForexLive",
        "section_url": "https://www.forexlive.com/",
        "rss_url": "https://www.forexlive.com/feed/news",
        "allowed_domains": ("www.forexlive.com", "forexlive.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CoinDesk",
        "section_url": "https://www.coindesk.com/",
        "rss_url": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "allowed_domains": ("www.coindesk.com", "coindesk.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Cointelegraph",
        "section_url": "https://cointelegraph.com/",
        "rss_url": "https://cointelegraph.com/rss",
        "allowed_domains": ("cointelegraph.com", "www.cointelegraph.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Economic Times Markets",
        "section_url": "https://economictimes.indiatimes.com/markets",
        "rss_url": "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
        "allowed_domains": ("economictimes.indiatimes.com",),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Livemint Markets",
        "section_url": "https://www.livemint.com/market",
        "rss_url": "https://www.livemint.com/rss/markets",
        "allowed_domains": ("www.livemint.com", "livemint.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "NPR Economy",
        "section_url": "https://www.npr.org/sections/economy/",
        "rss_url": "https://feeds.npr.org/1017/rss.xml",
        "allowed_domains": ("www.npr.org", "npr.org"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Sky News Business",
        "section_url": "https://news.sky.com/business",
        "rss_url": "https://feeds.skynews.com/feeds/rss/business.xml",
        "allowed_domains": ("news.sky.com", "sky.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Moscow Times Business",
        "section_url": "https://www.themoscowtimes.com/business",
        "rss_url": "https://www.themoscowtimes.com/rss/business",
        "allowed_domains": ("www.themoscowtimes.com", "themoscowtimes.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Reuters Business",
        "section_url": "https://www.reuters.com/business/",
        "allowed_domains": ("www.reuters.com", "reuters.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Reuters Markets",
        "section_url": "https://www.reuters.com/markets/",
        "allowed_domains": ("www.reuters.com", "reuters.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Reuters World",
        "section_url": "https://www.reuters.com/world/",
        "allowed_domains": ("www.reuters.com", "reuters.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Bloomberg Markets",
        "section_url": "https://www.bloomberg.com/markets",
        "allowed_domains": ("www.bloomberg.com", "bloomberg.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Bloomberg Economics",
        "section_url": "https://www.bloomberg.com/economics",
        "allowed_domains": ("www.bloomberg.com", "bloomberg.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Barron's",
        "section_url": "https://www.barrons.com/",
        "rss_url": "https://feeds.content.dowjones.io/public/rss/mgBarrons",
        "allowed_domains": ("www.barrons.com", "barrons.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Economist Finance",
        "section_url": "https://www.economist.com/finance-and-economics",
        "allowed_domains": ("www.economist.com", "economist.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Fortune",
        "section_url": "https://fortune.com/",
        "rss_url": "https://fortune.com/feed/",
        "allowed_domains": ("fortune.com", "www.fortune.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Business Insider",
        "section_url": "https://www.businessinsider.com/s",
        "rss_url": "https://www.businessinsider.com/rss",
        "allowed_domains": ("www.businessinsider.com", "businessinsider.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CNN Business",
        "section_url": "https://www.cnn.com/business",
        "rss_url": "http://rss.cnn.com/rss/money_latest.rss",
        "allowed_domains": ("www.cnn.com", "cnn.com", "money.cnn.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CNN World",
        "section_url": "https://www.cnn.com/world",
        "rss_url": "http://rss.cnn.com/rss/edition_world.rss",
        "allowed_domains": ("www.cnn.com", "cnn.com", "edition.cnn.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Fox Business",
        "section_url": "https://www.foxbusiness.com/",
        "rss_url": "https://moxie.foxbusiness.com/google-publisher/markets.xml",
        "allowed_domains": ("www.foxbusiness.com", "foxbusiness.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "ABC News Business",
        "section_url": "https://abcnews.go.com/Business",
        "rss_url": "https://abcnews.go.com/abcnews/businessheadlines",
        "allowed_domains": ("abcnews.go.com",),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CBS MoneyWatch",
        "section_url": "https://www.cbsnews.com/moneywatch/",
        "rss_url": "https://www.cbsnews.com/latest/rss/moneywatch",
        "allowed_domains": ("www.cbsnews.com", "cbsnews.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "NBC Business",
        "section_url": "https://www.nbcnews.com/business",
        "rss_url": "https://feeds.nbcnews.com/nbcnews/public/business",
        "allowed_domains": ("www.nbcnews.com", "nbcnews.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "USA Today Money",
        "section_url": "https://www.usatoday.com/money/",
        "rss_url": "https://rssfeeds.usatoday.com/usatoday-NewsTopStories",
        "allowed_domains": ("www.usatoday.com", "usatoday.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "NYTimes Business",
        "section_url": "https://www.nytimes.com/section/business",
        "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
        "allowed_domains": ("www.nytimes.com", "nytimes.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "NYTimes Economy",
        "section_url": "https://www.nytimes.com/section/business/economy",
        "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml",
        "allowed_domains": ("www.nytimes.com", "nytimes.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Washington Post Business",
        "section_url": "https://www.washingtonpost.com/business/",
        "allowed_domains": ("www.washingtonpost.com", "washingtonpost.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Los Angeles Times Business",
        "section_url": "https://www.latimes.com/business",
        "rss_url": "https://www.latimes.com/business/rss2.0.xml",
        "allowed_domains": ("www.latimes.com", "latimes.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Politico Economy",
        "section_url": "https://www.politico.com/economy",
        "allowed_domains": ("www.politico.com", "politico.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Axios Markets",
        "section_url": "https://www.axios.com/markets",
        "rss_url": "https://api.axios.com/feed/markets.xml",
        "allowed_domains": ("www.axios.com", "axios.com", "api.axios.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Semafor Business",
        "section_url": "https://www.semafor.com/business",
        "rss_url": "https://www.semafor.com/rss.xml",
        "allowed_domains": ("www.semafor.com", "semafor.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Quartz",
        "section_url": "https://qz.com/",
        "rss_url": "https://qz.com/rss",
        "allowed_domains": ("qz.com", "www.qz.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "TechCrunch",
        "section_url": "https://techcrunch.com/",
        "rss_url": "https://techcrunch.com/feed/",
        "allowed_domains": ("techcrunch.com", "www.techcrunch.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Verge Business",
        "section_url": "https://www.theverge.com/business",
        "rss_url": "https://www.theverge.com/rss/index.xml",
        "allowed_domains": ("www.theverge.com", "theverge.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Wired Business",
        "section_url": "https://www.wired.com/category/business/",
        "rss_url": "https://www.wired.com/feed/rss",
        "allowed_domains": ("www.wired.com", "wired.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Ars Technica Business",
        "section_url": "https://arstechnica.com/gadgets/",
        "rss_url": "https://feeds.arstechnica.com/arstechnica/index",
        "allowed_domains": ("arstechnica.com", "www.arstechnica.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Seeking Alpha Market News",
        "section_url": "https://seekingalpha.com/market-news",
        "rss_url": "https://seekingalpha.com/market_currents.xml",
        "allowed_domains": ("seekingalpha.com", "www.seekingalpha.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Morningstar Markets",
        "section_url": "https://www.morningstar.com/markets",
        "allowed_domains": ("www.morningstar.com", "morningstar.com"),
        "language": "en",
        "translate_to_russian": True,
    },
    {
        "name": "Benzinga Markets",
        "section_url": "https://www.benzinga.com/markets",
        "rss_url": "https://www.benzinga.com/feed",
        "allowed_domains": ("www.benzinga.com", "benzinga.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Zacks",
        "section_url": "https://www.zacks.com/stock/news",
        "rss_url": "https://www.zacks.com/commentary/rss",
        "allowed_domains": ("www.zacks.com", "zacks.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Motley Fool",
        "section_url": "https://www.fool.com/investing-news/",
        "rss_url": "https://www.fool.com/feeds/index.aspx",
        "allowed_domains": ("www.fool.com", "fool.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "FXStreet News",
        "section_url": "https://www.fxstreet.com/news",
        "rss_url": "https://www.fxstreet.com/rss/news",
        "allowed_domains": ("www.fxstreet.com", "fxstreet.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "DailyFX",
        "section_url": "https://www.dailyfx.com/",
        "rss_url": "https://www.dailyfx.com/feeds/all",
        "allowed_domains": ("www.dailyfx.com", "dailyfx.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Decrypt",
        "section_url": "https://decrypt.co/news",
        "rss_url": "https://decrypt.co/feed",
        "allowed_domains": ("decrypt.co", "www.decrypt.co"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CryptoSlate",
        "section_url": "https://cryptoslate.com/news/",
        "rss_url": "https://cryptoslate.com/feed/",
        "allowed_domains": ("cryptoslate.com", "www.cryptoslate.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Bitcoin Magazine",
        "section_url": "https://bitcoinmagazine.com/",
        "rss_url": "https://bitcoinmagazine.com/.rss/full/",
        "allowed_domains": ("bitcoinmagazine.com", "www.bitcoinmagazine.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Blockworks",
        "section_url": "https://blockworks.co/news",
        "rss_url": "https://blockworks.co/feed",
        "allowed_domains": ("blockworks.co", "www.blockworks.co"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Euronews Business",
        "section_url": "https://www.euronews.com/business",
        "rss_url": "https://www.euronews.com/rss?level=theme&name=business",
        "allowed_domains": ("www.euronews.com", "euronews.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "DW Business",
        "section_url": "https://www.dw.com/en/business/s-1431",
        "rss_url": "https://rss.dw.com/xml/rss-en-bus",
        "allowed_domains": ("www.dw.com", "dw.com", "rss.dw.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Al Jazeera Economy",
        "section_url": "https://www.aljazeera.com/economy/",
        "rss_url": "https://www.aljazeera.com/xml/rss/all.xml",
        "allowed_domains": ("www.aljazeera.com", "aljazeera.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "France24 Business",
        "section_url": "https://www.france24.com/en/business-tech/",
        "rss_url": "https://www.france24.com/en/business-tech/rss",
        "allowed_domains": ("www.france24.com", "france24.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Nikkei Asia Business",
        "section_url": "https://asia.nikkei.com/Business",
        "rss_url": "https://asia.nikkei.com/rss/feed/nar",
        "allowed_domains": ("asia.nikkei.com",),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Japan Times Business",
        "section_url": "https://www.japantimes.co.jp/business/",
        "rss_url": "https://www.japantimes.co.jp/business/feed/",
        "allowed_domains": ("www.japantimes.co.jp", "japantimes.co.jp"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "SCMP Business",
        "section_url": "https://www.scmp.com/business",
        "rss_url": "https://www.scmp.com/rss/2/feed",
        "allowed_domains": ("www.scmp.com", "scmp.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Channel NewsAsia Business",
        "section_url": "https://www.channelnewsasia.com/business",
        "rss_url": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6936",
        "allowed_domains": ("www.channelnewsasia.com", "channelnewsasia.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Straits Times Business",
        "section_url": "https://www.straitstimes.com/business",
        "rss_url": "https://www.straitstimes.com/news/business/rss.xml",
        "allowed_domains": ("www.straitstimes.com", "straitstimes.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Australian Financial Review",
        "section_url": "https://www.afr.com/",
        "rss_url": "https://www.afr.com/rss",
        "allowed_domains": ("www.afr.com", "afr.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "CBC Business",
        "section_url": "https://www.cbc.ca/news/business",
        "rss_url": "https://www.cbc.ca/cmlink/rss-business",
        "allowed_domains": ("www.cbc.ca", "cbc.ca"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Financial Post",
        "section_url": "https://financialpost.com/",
        "rss_url": "https://financialpost.com/feed/",
        "allowed_domains": ("financialpost.com", "www.financialpost.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "The Globe and Mail Business",
        "section_url": "https://www.theglobeandmail.com/business/",
        "rss_url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/business/",
        "allowed_domains": ("www.theglobeandmail.com", "theglobeandmail.com"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
    {
        "name": "Swissinfo Business",
        "section_url": "https://www.swissinfo.ch/eng/business/",
        "rss_url": "https://www.swissinfo.ch/eng/rss",
        "allowed_domains": ("www.swissinfo.ch", "swissinfo.ch"),
        "language": "en",
        "translate_to_russian": True,
        "min_article_words": 35,
        "allow_rss_content_fallback": True,
    },
)
