# Generated by Django 4.2.23 on 2025-11-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('main', '0001_initial'),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterUniqueTogether(
            name='usertokens',
            unique_together={('username', 'token')},
        ),
    ]
